services:
  api-gateway:
    build:
      context: .
      dockerfile: ./apps/api-gateway/Dockerfile
      target: development
    command: pnpm run start:dev api-gateway
    env_file:
      - ./apps/api-gateway/.env
    environment:
      - AUTH_HTTP_BASEURL=http://auth:3001
      - ORDERS_HTTP_BASEURL=http://orders:3003
    ports:
      - '3000:3000'
    depends_on:
      - auth
      - orders
    volumes:
      - .:/usr/src/app

  auth:
    build:
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    command: pnpm run start:dev auth
    env_file:
      - ./apps/auth/.env
    ports:
      - '3001:3001'
    volumes:
      - .:/usr/src/app

  products:
    build:
      context: .
      dockerfile: ./apps/products/Dockerfile
      target: development
    command: pnpm run start:dev products
    ports:
      - '3002:3002'
    volumes:
      - .:/usr/src/app

  orders:
    build:
      context: .
      dockerfile: ./apps/orders/Dockerfile
      target: development
    command: pnpm run start:dev orders
    environment:
      - MONGODB_URI=mongodb://mongo:27017/orders
      - HTTP_PORT=3003
      - PRODUCTS_HTTP_BASEURL=http://products:3002
    ports:
      - '3003:3003'
    depends_on:
      - mongo
      - products
    env_file:
      - ./apps/products/.env
    environment:
      - MONGODB_URI=mongodb://mongo:27017/products
    ports:
      - '3002:3002'
    depends_on:
      - mongo
    volumes:
      - .:/usr/src/app

  mongo:
    image: mongo
    ports:
      - '27017:27017'

  # mongodb:
  #   image: mongodb
  #   container_name: mongodb
  #   ports:
  #     - '27017:27017'
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: admin
  #     MONGO_INITDB_ROOT_PASSWORD: admin123
